// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkTgRmyiluhrGQe3q7YYG-PubT3PLMJQU',
    appId: '1:140500355589:web:9044aa9731a9ba29836a6c',
    messagingSenderId: '140500355589',
    projectId: 'tailmate-cd79c',
    authDomain: 'tailmate-cd79c.firebaseapp.com',
    storageBucket: 'tailmate-cd79c.appspot.com',
    measurementId: 'G-46DSNBT5Y7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYlcVx4eKy0l7y2ZFCNE-NSQLRXRrYBew',
    appId: '1:140500355589:android:6f773dd9265f8101836a6c',
    messagingSenderId: '140500355589',
    projectId: 'tailmate-cd79c',
    storageBucket: 'tailmate-cd79c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzWS33hFQbDTTpiV1meq0928bN2ywT8Fc',
    appId: '1:140500355589:ios:a0608be511583ad1836a6c',
    messagingSenderId: '140500355589',
    projectId: 'tailmate-cd79c',
    storageBucket: 'tailmate-cd79c.appspot.com',
    androidClientId: '140500355589-o9vrttlnfmgsg8vact3lka7m157ilf18.apps.googleusercontent.com',
    iosClientId: '140500355589-va10n9t7vjrua8moitdv2l3l42dlvn2i.apps.googleusercontent.com',
    iosBundleId: 'com.example.tailmate',
  );
}
